.travis.yml, appinfo/info.xml, lib/Sabre/AbstractBearer.php, lib/Sabre/OAuth2.php, tests/Unit/Sabre/AbstractBearerTest.php
To add compatibility with ownCloud 9.1 the class `AbstractBearer` was imported from sabre/dav 3.2. This was necessary, because in ownCloud 9.1 an older version of this library is being used.
This Pull Request can only be built successfully if Pull Request [core#27370](https://github.com/owncloud/core/pull/27370) is going to be merged.
=> Add compatibility with ownCloud 9.1

appinfo/Migrations/Version20170329194544.php, appinfo/database.xml, appinfo/info.xml
=> Add default client ids for desktop and mobile clients

js/login.js, lib/AppInfo/Application.php
=> The user is set on the login screen if transmitted from the client

appinfo/Migrations/Version20170724162518.php, appinfo/info.xml, lib/Controller/OAuthApiController.php, lib/Controller/PageController.php, lib/Db/RefreshToken.php, tests/Unit/Controller/OAuthApiControllerTest.php, tests/Unit/Controller/SettingsControllerTest.php, tests/Unit/Db/RefreshTokenMapperTest.php
=> allow creation of multiple access tokens per client id

js/login.js
This is to avoid what's described in https://github.com/owncloud/oauth2/issues/74: auto-filling the username on the login form in LDAP UUID setups prevented the user (from the Desktop client) to re-login.
Not an optimal solution from an UX POV, but at least does not completely breaks the re-authentication from on the Desktop client.
=> Removing readonly property from the username on the login form

lib/Controller/OAuthApiController.php, lib/Db/AccessToken.php, lib/Db/AuthorizationCode.php, tests/Unit/Controller/OAuthApiControllerTest.php, tests/Unit/Controller/PageControllerTest.php, tests/Unit/Db/AccessTokenTest.php, tests/Unit/Db/AuthorizationCodeTest.php
Just so we get a unique reference of this value (e.g. the 'expires_in' value
on the access token JSON response was not bounded to the actual value, but
duplicated there).
Disclaimer: my PHP-fu is close to non-existent.
=> Move all hardcoded expiration deltas to constants

tests/acceptance/features/bootstrap/Oauth2Context.php
Issue #159 
Before https://github.com/owncloud/core/pull/32505 an exception was thrown on Client/Server errors. We don't do that any-more, because the higher layers might just expect that error. But now we need to check the error code in the result and not rely on the exception
=> don't expect exception from WebDavHelper::makeDavRequest

appinfo/info.xml, lib/AuthModule.php, lib/Commands/AddClient.php, lib/Controller/PageController.php, tests/Unit/Controller/PageControllerTest.php
Fixes #165 
0. add a new client using the occ command
```
./occ oauth2:add-client test clientid-1234567890-1234567890-1234567890 secret-secret-secret-secret-secret http://localhost:9999
```
1. open browser
http://own.cloud.local/index.php/apps/oauth2/authorize?response_type=token&client_id=clientid-1234567890-1234567890-1234567890&redirect_uri=http://localhost:9999
2. See authorization dialog - click button 'Authorize'
3. See login dialog - login
4. See redirect to url http://localhost:9999/?access_token=BBtaHzdCpXoRnN912G7hCPVcSHLSpKZbVF5tuwaLgxajj3mbpik7m2MHJOty1Vxk&expires_in=3600
5. this access_token can now be used to call e.g.
```sh
curl -v http://own.cloud.local/index.php/apps/oauth2/api/v1/arer BBtaHzdCpXoRnN912G7hCPVcSHLSpKZbVF5tuwaLgxajj3mbpik7m2MHJOty1Vxk'
=> Add support for implicit grant

.drone.yml, appinfo/info.xml, tests/Unit/Sabre/AbstractBearerTest.php
1) Bump max-version to 11.0.0.0 like we did with all other apps
2) Copy changes from https://github.com/sabre-io/dav/blob/master/tests/Sabre/DAV/Auth/Backend/AbstractBearerTest.php to make unit tests pass against core master
3) The last 2 drone matrix entries were identical, testing PHP 7.2 with core master - change one of them so it tests with PHP 7.1
=> Bump max-version to 11.0.0.0

tests/acceptance/features/lib/Oauth2AuthRequestPage.php
Old forms of the constant names were deprecated by https://github.com/owncloud/core/pull/32781/commits/db4608ace28ed62a00173021416951fb7ac3d994
Use the new forms that have underscores.
=> adjust acceptance test time constant names

Makefile
1) ``all`` target was doing nothing - make ``help`` be the default target.
2) Move the ``vendor-bin`` cleaning into ``clean-composer-deps`` ssection
3) ``composer_deps=vendor`` so that the ``vendor`` dir also gets removed
=> Delete vendor when doing clean-deps

lib/Controller/PageController.php
Without this urlencode the redirect_uri is getting lost on switching users.
=> The redirect_uri needs to be encoded in the logout url

tests/acceptance/features/bootstrap/Oauth2Context.php
because of changes in https://github.com/owncloud/core/pull/34554/ `SRC_SKELETON_DIR` is not the full path to the skeleton folder any more. And we should use the testing app to read files from the skeleton anyway.
needs https://github.com/owncloud/core/pull/34579 and https://github.com/owncloud/core/pull/34581
=> read the skeleton file through the testing app not directly

.drone.yml, appinfo/info.xml, vendor-bin/behat/composer.json
core stable10 no longer supports PHP 5.6
https://github.com/owncloud/core/pull/34698
=> Drop PHP 5.6

composer.json, composer.lock
Add the `platform` section in `composer.json` like we do in other apps.
In this case it does not make a difference to which versions of dependencies are chosen, but one day it might.
The other parts of dropping PHP 5.6 were all done in #202 already.
=> Adjust composer files to specify PHP 7.0.8

composer.lock, phpunit.xml, tests/Unit/AuthModuleTest.php, tests/Unit/BackgroundJob/CleanUpTest.php, tests/Unit/Controller/OAuthApiControllerTest.php, tests/Unit/Controller/OpenIdConnectControllerTest.php, tests/Unit/Controller/PageControllerTest.php, tests/Unit/Controller/SettingsControllerTest.php, tests/Unit/Db/AccessTokenMapperTest.php, tests/Unit/Db/AccessTokenTest.php, tests/Unit/Db/AuthorizationCodeMapperTest.php, tests/Unit/Db/AuthorizationCodeTest.php, tests/Unit/Db/ClientMapperTest.php, tests/Unit/Db/RefreshTokenMapperTest.php, tests/Unit/Hooks/UserHooksTest.php, tests/Unit/Sabre/OAuth2Test.php, tests/Unit/UtilitiesTest.php, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/Oauth2Context.php
1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) phpunit enable failOnRisky failOnWarning 
3) remove unused use statements 
4) Updating bamarni/composer-bin-plugin (v1.2.0 => v1.3.0)
=> Phpunit 5 6

.drone.yml
because the syntax `db_name: ${DB_NAME=owncloud}` does not get substituted properly by the automatic drone convert for the new drone version.
=> Specify Oracle DB name directly

lib/Controller/OAuthApiController.php
The refresh and access token won't be deleted if the user is disabled
(access token might still expire). The access token will be considered
as invalid if the user is disabled
This fixes a problem with the android client when the user is disabled. The duplicated auth exception won't happen
=> Handle refresh token of a disabled user

css/main.css, js/settings-admin.js, lib/Commands/AddClient.php, lib/Controller/SettingsController.php, lib/Db/ClientMapper.php, lib/Panels/AdminPanel.php, templates/authorize.php, templates/client.part.php, templates/settings-admin.php, templates/settings-personal.php, tests/Unit/Controller/SettingsControllerTest.php, tests/Unit/Panel/AdminPanelTest.php, tests/acceptance/features/lib/Oauth2AdminSettingsPage.php
-  [x] Fixes error 500 for web UI and unhandled `unqiueConstraintViolation` in CLI when a client with a duplicated name is added
Closes  https://github.com/owncloud/oauth2/issues/234  https://github.com/owncloud/oauth2/issues/162 https://github.com/owncloud/oauth2/issues/135
=> Improve adding a new client

tests/acceptance/features/bootstrap/Oauth2Context.php
This PR fixes https://drone.owncloud.com/owncloud/oauth2/848/12/11 caused due to https://github.com/owncloud/core/pull/36600
- Fixes https://github.com/owncloud/oauth2/issues/246
=> Fix: fail due to unneeded variable removal in webDavHelper

tests/acceptance/features/bootstrap/Oauth2Context.php, tests/acceptance/features/webUIOauth2/enforceTokenAuth.feature, tests/acceptance/features/webUIOauth2/newClientRegistration.feature, tests/acceptance/features/webUIOauth2/obtainAccessToken.feature, tests/acceptance/features/webUIOauth2/revokeAccessToken.feature
Similar to what was done in core recently.
1) Adjust some step text so we can write `When user "user1"
2) Fix an error in a scenario that accidentally used `user1` that does not exist anyway.
3) Use realistic usernames
=> Use realistic usernames

phpstan.neon
The PHPdoc of `OC\\Template\\Base::assign()` was fixed in core yesterday PR https://github.com/owncloud/core/pull/37503 so the "error" no longer needs to be ignored.
=> Adjust phpstan.neon so it passes

.drone.star, appinfo/info.xml, composer.json, composer.lock, vendor-bin/behat/composer.json
Issue https://github.com/owncloud/core/issues/38067
See issue for details - `behat` acceptance tests need to use PHP 7.4 for the dependencies to sort themselves out with composer 2.0
And bump PHP to 7.1 in `composer.json` and core min version to 10.3 - we are not going to realistically support PHP 7.0 and core 10.2 for the next release of this app.
=> Adjust PHP dependencies for composer 2.0

appinfo/Migrations/Version20201126140622.php, appinfo/info.xml, lib/Controller/OAuthApiController.php, lib/Controller/PageController.php, lib/Db/AuthorizationCode.php, lib/Exceptions/UnsupportedPkceTransformException.php, lib/Utilities.php, tests/Unit/Controller/OAuthApiControllerTest.php, tests/Unit/Db/AuthorizationCodeTest.php, tests/Unit/UtilitiesTest.php
Implemented the PKCE extension according to the [RFC 7636](https://tools.ietf.org/pdf/rfc7636.pdf)
I tested it with the latest desktop client and the Android App and both worked.
It should also still work for clients which do not send the PKCE parameters.
=> implement the oauth2 pkce extension

lib/AppInfo/Application.php
This PHPdoc of `\OCA\OAuth2\Db\Client ` was somehow duplicated. `phpstan` started noticing:
```
php -d zend.enable_gc=0 vendor-bin/phpstan/vendor/bin/phpstan analyse --memory-limit=4G --configuration=./phpstan.neon --no-progress --level=5 appinfo lib
------ ----------------------------------------------------- 
Line   lib/AppInfo/Application.php                          
------ ----------------------------------------------------- 
108    Variable $client in PHPDoc tag @var does not exist.  
------ ----------------------------------------------------- 
[ERROR] Found 1 error                                                          
```
Remove the duplcation.
=> Remove duplicate PHPdoc

lib/Controller/OAuthApiController.php, lib/Controller/PageController.php
Dear Owncloud team,
we use the `user_ldap` backend against Active Directory, and we have it configured with `ldap_expert_uuid_user_attr` = `objectguid` and `ldap_expert_username_attr` blank, thus the internal owncloud IDs are the AD GUIDs, but users log on with their `sAMAccountName`.
This causes a discrepancy in the OAuth login flow, as the user identifier passed along the flow is the user name, that doesn't match with the user UID that all the Desktop, iOS and Android clients expect.
Armed with much desire to have this fixed and with little knowledge of OC internals, I made this adaptation that seem to work well with our use case - but it looks also generic enough to be included upstream.
Thank you for your consideration,
=> Support setups with user login name != internal UID

appinfo/Migrations/Version20201123114127.php, lib/Commands/AddClient.php, lib/Controller/PageController.php, lib/Controller/SettingsController.php, lib/Db/Client.php, lib/Utilities.php, templates/client.part.php, templates/settings-admin.php, tests/Unit/Controller/PageControllerTest.php, tests/Unit/Controller/SettingsControllerTest.php, tests/acceptance/features/bootstrap/Oauth2Context.php, tests/acceptance/features/lib/Oauth2AdminSettingsPage.php
I'm reopening https://github.com/owncloud/oauth2/pull/275 because setting a client as trusted makes sense in certain situations like for web clients.
This change introduces the options to set a client as trusted and therefor skip the consent step.
https://auth0.com/docs/authorization/user-consent-and-third-party-applications#skip-consent-for-first-party-applications
=> Add support for trusted clients

tests/acceptance/features/bootstrap/Oauth2Context.php, tests/acceptance/features/bootstrap/bootstrap.php, tests/acceptance/features/lib/Oauth2AdminSettingsPage.php, tests/acceptance/features/lib/Oauth2AuthRequestPage.php, tests/acceptance/features/lib/Oauth2OnPersonalSecuritySettingsPage.php
Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script
=> [Tests-Only] enforce strict type checking in acceptace tests code

lib/Controller/OAuthApiController.php, lib/Controller/PageController.php
fixes https://github.com/owncloud/oauth2/issues/326 by partly reverting https://github.com/owncloud/oauth2/pull/286/files#diff-c88f37beed53f2aeb9db529d2af61368ae49ec6052aa091a062023ae9cfcc670L249-R259 and filling the login form with the login name in the web ui.
The userid should always be used on the api. Clients should use the displayname or email properties that can be accessed via the ocs api.
=> use userid on api calls, show username in login form

js/login.js, lib/AppInfo/Application.php
The oauth2 app uses js to fill the login with the user from the redirect url. Why exactly I don't know. The LoginController in core already picks up a `user` parameter and fills the login form username with it. AFAICT the code picks up the user from the redirect url. Who knows where that is used.
In any case this PR looks up the user and uses the username instead of the userid. Similar to https://github.com/owncloud/core/pull/39870
=> Fill login_hint with username

lib/Controller/OAuthApiController.php
The authorization code flow doesn't require a client secret in case of a public client. Instead, the client needs to use the PKCE extension and send a code challenge / code verifier.
That is why we don't compare the client secret when the client id and code verifier are set in the query parameters.
/cc @dschmidt
=> don't require client secret when using PKCE
