owncloud/oauth2

templates/settings-admin.php
If-clause writes a message if there are no registered clients.
=> Add if-clause

lib/Controller/OAuthApiController.php, tests/Unit/Controller/OAuthApiControllerTest.php
Updating the JSON Errormessages and related tests according to
https://tools.ietf.org/html/rfc6749#section-5.2
=> Improvements

lib/Controller/SettingsController.php, lib/Utilities.php, templates/settings-admin.php, tests/Unit/UtilitiesTest.php
fixes https://github.com/owncloud/oauth2/issues/29
=> Allow http://localhost:* as valid redirect url

lib/Db/ClientMapper.php
=> Use prefix properly 

lib/AppInfo/Application.php, lib/AuthModule.php, lib/Sabre/OAuth2.php, tests/Unit/Sabre/OAuth2Test.php
fixes https://github.com/owncloud/core/issues/28336
=> Verify the token even for cookie based auth

README.md, appinfo/routes.php, css/authorization.css, lib/Controller/OAuthApiController.php, lib/Controller/PageController.php, templates/authorization-successful.php, templates/authorize.php, tests/Unit/Controller/OAuthApiControllerTest.php, tests/Unit/Controller/PageControllerTest.php
=> Add authorization successful message

templates/authorize-error.php, templates/authorize.php
=> Remove cancel button on authorize page and fix some texts 

css/authorization.css, lib/Controller/PageController.php, templates/authorization-successful.php, templates/authorize-error.php, templates/authorize.php, templates/switch-user.php
=> Style authorize page to look more like ownCloud

templates/authorize-error.php, templates/switch-user.php
=> Fix button handling

js/settings.js
=> There is an event object to be passed into the handler

appinfo/info.xml
Documentation is missing as we don't have anything yet.
Screenshot is still empty. Following are two screenshots that still need to be checked regarding dimensions. Please check and upload @hurradieweltgehtunter, then we can insert here and merge. Thanks!
Btw. I can't make @tobiherr a reviewer here :/
=> Change summary, description and category, add website, bugs, repository

js/switch-user.js, lib/Controller/PageController.php, tests/Unit/Controller/PageControllerTest.php
=> Print displayname of the user in the switch user page

templates/switch-user.php
there is no need in adding a strong tag in the template since the variable itself is html already which holds the strong tag
=> fix double strong tag

appinfo/info.xml
Please let me merge this to leave some time for others to vote on the image.
=> add title screenshot

.gitignore, .travis.yml, CHANGELOG.md, Makefile, appinfo/Migrations/Version20170724162518.php, appinfo/info.xml
- create release branch
- better Makefile
=> Release Changes for master 

CHANGELOG.md, appinfo/info.xml
bring updates from release process back into dev branch
=> Backflow of changes from release process

lib/AuthModule.php, tests/Unit/AuthModuleTest.php
fixes #103 
requires https://github.com/owncloud/core/pull/30365
=> Throw an exception if the Bearer header holds an invalid token

lib/AuthModule.php, lib/Controller/OAuthApiController.php
If you need to find out why tokens are invalid ...
=> more logging

CHANGELOG.md, appinfo/info.xml
=> [WIP prepare 0.2.2 release

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/Oauth2Context.php, tests/acceptance/features/bootstrap/bootstrap.php, tests/acceptance/features/lib/Oauth2AuthRequestPage.php, tests/acceptance/features/webUIOauth2/accessToken.feature
first iteration of acceptance tests for the oauth app
should tick a couple of boxes in the test-plan https://github.com/owncloud/QA/blob/master/Server/Test_Plan_OAuth2.md
=> acceptance tests

tests/acceptance/features/bootstrap/Oauth2Context.php, tests/acceptance/features/webUIOauth2/accessToken.feature
two small tests to check if OCS works with oauth
depends on https://github.com/owncloud/core/pull/31354 being merged and a new QA tarball build
=> test use oauth for OCS

tests/acceptance/features/bootstrap/Oauth2Context.php, tests/acceptance/features/webUIOauth2/obtainAccessToken.feature, tests/acceptance/features/webUIOauth2/revokeAccessToken.feature
a couple of security relevant tests, more to follow
=> test correct usage of tokens

tests/acceptance/features/bootstrap/Oauth2Context.php, tests/acceptance/features/lib/Oauth2AdminSettingsPage.php, tests/acceptance/features/webUIOauth2/newClientRegistration.feature
tests to check if a new client can be registered via webUI and if the new client-id and client-secret can be used to obtain tokens
depends on https://github.com/owncloud/core/pull/31412 and https://github.com/owncloud/core/pull/31420 being merged and new QA builds made
=> acceptance tests for newly registered clients

README.md
the client can also send the username and the desktop client actually does
so would be good to document it
=> document user parameter in Authorization Request

.drone.yml, tests/acceptance/config/behat.yml
1. Use the ocPath that sends occ commands through the testing app
1. Use the core run.sh script to run the acceptance tests
=> follow CI changes made in core

CHANGELOG.md, appinfo/info.xml
=> Release 0.2.3

.travis.yml
Add PHP 7.1 and 7.2 to stable10 tests for mysql Database
=> Add PHP 7.1 and 7.2 to stable10 tests

README.md
=> Adjust build status badge to drone

templates/authorize-error.php, templates/authorize.php, templates/switch-user.php
Autofocus added to buttons, so you can directly push 'enter' after successful login without having to tab.
=> Autofocus added to buttons

CHANGELOG.md, appinfo/info.xml
Closes https://github.com/owncloud/oauth2/issues/181
=> Release 0.3.0

Makefile, phpcs.xml, tests/acceptance/features/bootstrap/Oauth2Context.php, vendor-bin/php_codesniffer/composer.json
Like was merged in core in https://github.com/owncloud/core/pull/34191
So that we know if we break our own rules for acceptance test code style.
=> Add php codesniffer

lib/Controller/OAuthApiController.php, tests/Unit/Controller/OAuthApiControllerTest.php
Handle the case where the user associated to the token is disabled. Both the authorization_code and refresh_token will fail with a 400 status and a "unauthorized_client" error instead of returning a valid access token
Related to https://github.com/owncloud/client/issues/7212 and https://github.com/owncloud/enterprise/issues/2509
=> Check user status

CHANGELOG.md, appinfo/info.xml
=> Release 0.4.1 

tests/acceptance/features/webUIOauth2/enforceTokenAuth.feature, tests/acceptance/features/webUIOauth2/newClientRegistration.feature, tests/acceptance/features/webUIOauth2/obtainAccessToken.feature, tests/acceptance/features/webUIOauth2/revokeAccessToken.feature
=> Adjust create user test steps

.drone.yml
Add drone matrices to run test against latest stable release tarball.
Related Issue https://github.com/owncloud/QA/issues/611
=> Run acceptance tests in latest stable release of core

.drone.starlark, .drone.yml, tests/Unit/AuthModuleTest.php, tests/Unit/Controller/OAuthApiControllerTest.php, tests/Unit/Controller/OpenIdConnectControllerTest.php, tests/Unit/Controller/PageControllerTest.php, tests/Unit/Controller/SettingsControllerTest.php, tests/Unit/Db/AccessTokenMapperTest.php, tests/Unit/Db/AccessTokenTest.php, tests/Unit/Db/AuthorizationCodeMapperTest.php, tests/Unit/Db/AuthorizationCodeTest.php, tests/Unit/Db/ClientMapperTest.php, tests/Unit/Db/RefreshTokenMapperTest.php, tests/Unit/Hooks/UserHooksTest.php, tests/Unit/Panel/AdminPanelTest.php, tests/Unit/Sabre/OAuth2Test.php, vendor-bin/behat/composer.json
Similar to https://github.com/owncloud/configreport/pull/121
=> Adjust tests 

.drone.starlark, tests/Unit/AuthModuleTest.php, tests/Unit/Db/AccessTokenMapperTest.php, tests/Unit/Db/AuthorizationCodeMapperTest.php, tests/Unit/Db/ClientMapperTest.php, tests/Unit/Db/RefreshTokenMapperTest.php, vendor-bin/owncloud-codestyle/composer.json
like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
Note: there was no effect here on `.drone.yml`
=> Coding standard 2.0.0

CHANGELOG.md, appinfo/info.xml
=> Merge Release 0.4.3

tests/acceptance/features/bootstrap/Oauth2Context.php, tests/acceptance/features/lib/Oauth2AdminSettingsPage.php
This PR fixes the test fails due to core changes.
- Fixes https://github.com/owncloud/oauth2/issues/249
=> fails due to core changes fixed

tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/Oauth2Context.php
Fix method calls from `Oauth2Context` to `FeatureContext` due to recent refactoring on core.
=> [Tests-only] Fix method calls for changes to feature context in core

.drone.star, .phan/config.php, lib/AppInfo/Application.php, lib/AuthModule.php, lib/Commands/AddClient.php, lib/Commands/RemoveClient.php, lib/Controller/OAuthApiController.php, lib/Controller/PageController.php, lib/Controller/SettingsController.php, lib/Db/AccessTokenMapper.php, lib/Hooks/UserHooks.php, lib/Panels/AdminPanel.php, lib/Panels/PersonalPanel.php, lib/Sabre/OAuth2.php, vendor-bin/phan/composer.json
Part of https://github.com/owncloud/QA/issues/643
=> [Tests-Only] Bump phan 2.7 & Run phan in CI

.gitignore, tests/Unit/Controller/PageControllerTest.php, tests/Unit/Db/AccessTokenTest.php, tests/Unit/Db/AuthorizationCodeTest.php, tests/Unit/Panel/AdminPanelTest.php, vendor-bin/behat/composer.json, vendor-bin/phpstan/composer.json
Part of https://github.com/owncloud/QA/issues/647
=> Implement phpunit v8

lib/Commands/AddClient.php
Using a string value as default is the right thing to do - the code never treated this properly and was expecting a boolean value right away :see_no_evil:
=> allow-sub-domains is a string needs to be properly handled

.drone.star, CHANGELOG.md, appinfo/info.xml
=> Release 0.4.4

lib/Controller/OAuthApiController.php
fixes https://github.com/owncloud/enterprise/issues/4135
=> return proper error description for auth-core/refresh-token errors

tests/acceptance/features/webUIOauth2/enforceTokenAuth.feature, tests/acceptance/features/webUIOauth2/newClientRegistration.feature, tests/acceptance/features/webUIOauth2/obtainAccessToken.feature, tests/acceptance/features/webUIOauth2/revokeAccessToken.feature
like was done in core last week.
Fixes CI
=> [tests-only] Specify skeleton in tests

tests/acceptance/features/bootstrap/Oauth2Context.php
core PR https://github.com/owncloud/core/pull/39036 changed the parameters of various test helper functions. Adjust the calls.
=> [tests-only] [full-ci] Adjust calls to test helper functions

.drone.star, Makefile, composer.json, composer.lock, sonar-project.properties
Backport the CI changes from PR #302 to the release branch so that CI  can pass.
=> [tests-only] Update .drone.star and drop PHP 7.2

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
Merge back to master
Closes #308
=> Release 0.5.1

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Release 0.5.2

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Release 0.5.3

.github/ISSUE_TEMPLATE.md
=> org with com replaced

lib/Commands/AddClient.php, lib/Commands/ListClients.php, lib/Commands/ModifyClient.php, lib/Commands/RemoveClient.php
Symfony 5 will require this, so be prepared.
For Symfony 4 it is optional.
Preparation for https://github.com/owncloud/core/issues/39630
=> Always return an int from Symfony Command execute method

.drone.star
- remove the use of `drone_token`
- adjust the use of the `cache_s3` tokens to use the names now available
- Part of issue: https://github.com/owncloud/QA/issues/818
> Note: This PR was made by an automated script, in case something is not right I'll take care of it manually.
=> [full-ci] updated drone file oath2

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
Closes #357 
Oops, #359 already ask for another release.
=> Merge back release 0.6.0

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Merge back Release 0.6.1
